### ISSUE TITLE
Insufficient eyeballs

### ISSUE THREAD

**Issue by philoel** [galicae/advanced-scseq-2023#1]
Where are the eyes? How will the students become helplessly invested in photoreceptor evolution if you don't give them eyeballs?

**Comment by philoel** [comment]
ahhh this is not the course for "Advanced Eyeball Appreciation", my bad.

**Comment by galicae** [comment]
I am honestly more than happy to use eyeball datasets, if you can suggest a few that are *really well annotated* and we know the underlying biology rather well

**Comment by philoel** [comment]
https://elifesciences.org/articles/63907#s2 I recommend this with my whole heart. I've been using it extensively in my lamprey work and have also spent a lot of time exploring and updating annotations from this. 

In fact, the all the bipolar cell clusters (named "BP-1", "-2", etc.) are not yet annoated with some very major biology. I have done this and can give you ground truth, but the students might be able to work it out themselves too

**Comment by galicae** [comment]
Reminder to use [Lukowski et al.](https://pubmed.ncbi.nlm.nih.gov/31436334/) as comparison
